# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-table", "~> 0.12.0"

gem "tty-progressbar", "~> 0.18.2"

gem "tty-pie", "~> 0.4.0"

gem "rspec", "~> 3.10"

gem "curses", "~> 1.4"

gem "symmetric-encryption", "~> 4.3"

gem "tty-prompt", "~> 0.23.0"

gem "colorize", "~> 0.8.1"

gem "tty-cursor", "~> 0.7.1"
