# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"


gem "tty-table", "~> 0.12.0"

gem "tty-progressbar", "~> 0.18.2"

gem "tty-option", "~> 0.1.0"

gem "tty-pie", "~> 0.4.0"

gem "pastel", "~> 0.8.0"

gem "rspec", "~> 3.10"
